### Login as admin
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "admin@drx.com",
    "password": "admin123!"
}

### Get all employees
GET http://localhost:3000/api/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6IkFuYSBQYXZlbCIsImVtYWlsIjoidXNlcjJAZHJ4LmNvbSIsInJvbGUiOiJVU0VSIiwiZGVwdCI6MSwiaWF0IjoxNzc3NTcwOTc0LCJleHAiOjE3Nzc1OTk3NzR9.5ViKghA5jp0H-qoY8ku5DvHi3HKZ5vYBgOUUiIKgIMY

### Get all departments
GET http://localhost:3000/api/departments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6IkFuYSBQYXZlbCIsImVtYWlsIjoidXNlcjJAZHJ4LmNvbSIsInJvbGUiOiJVU0VSIiwiZGVwdCI6MSwiaWF0IjoxNzc3NTcwOTc0LCJleHAiOjE3Nzc1OTk3NzR9.5ViKghA5jp0H-qoY8ku5DvHi3HKZ5vYBgOUUiIKgIMY

### Get all assets
GET http://localhost:3000/api/assets/my-assets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6IkFuYSBQYXZlbCIsImVtYWlsIjoidXNlcjJAZHJ4LmNvbSIsInJvbGUiOiJVU0VSIiwiZGVwdCI6MSwiaWF0IjoxNzc3NTcwOTc0LCJleHAiOjE3Nzc1OTk3NzR9.5ViKghA5jp0H-qoY8ku5DvHi3HKZ5vYBgOUUiIKgIMY
